name: build-test

on:
  push:
    branches: [ test-actions ]
  pull_request:
    branches: [ trst-actions ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deps
      run: |
        sudo apt update
        sudo apt install -y bison
        sudo apt install -y ruby
        echo "Dependencies installed."
    
    - name: Main
      run: |
        git submodule init
        git submodule update --recursive
        mkdir build
        cd build
        cmake ..
        make
        
