name: BuildTest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      created

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deps
      run: |
        sudo apt update
        sudo apt install -y bison
        sudo apt install -y ruby
        sudo apt install -y libx11-dev
        sudo apt install -y libudev-dev
        sudo apt install -y libopenal-dev
        sudo apt install -y libvorbis-dev
        sudo apt install -y libflac-dev
        sudo apt install -y xorg-dev
        sudo apt install -y libglu1-mesa-dev
        sudo apt install -y g++-8
        sudo apt install -y gcc-8
        
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 999
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 999
        
        echo "Dependencies installed."
        g++ --version
    
    - name: Run
      run: |
        git submodule init
        git submodule update --recursive
        
        mkdir build
        cd build
        
        cmake ..
        make
        
        echo "Build completed."
        ./Launshi --version
        
